services:
  # PostgreSQL Database
  - type: pgsql
    name: papzincrew-db
    databaseName: papzincrew_music
    databaseUser: papzincrew_user
    plan: free

  # Backend API Service
  - type: web
    name: papzincrew-api
    env: python
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      # Database connection (automatically provided by Render when using pgsql service)
      - key: DATABASE_URL
        fromDatabase:
          name: papzincrew-db
          property: connectionString
      # Explicit Python version
      - key: PYTHON_VERSION
        value: "3.12.5"
      # Backblaze B2 Storage Configuration (set these in Render dashboard)
      - key: B2_ACCESS_KEY_ID
        value: ""  # Your Backblaze B2 Application Key ID
      - key: B2_SECRET_ACCESS_KEY
        value: ""  # Your Backblaze B2 Application Key
      - key: B2_BUCKET
        value: ""  # Your Backblaze B2 bucket name (e.g., papzincrew-music-djpapzin)
      # CORS Configuration
      - key: ALLOWED_ORIGINS
        value: "https://papzincrew.netlify.app,http://localhost:5173,http://localhost:5174,http://127.0.0.1:5173"
      - key: ALLOWED_ORIGIN_REGEX
        value: ""  # Optional regex for additional origins; defaults to localhost
      # Optional: Logging and Performance
      - key: LOG_LEVEL
        value: "INFO"
      - key: ENABLE_UPLOAD_PRINTS
        value: "0"  # Set to 1 for debug upload logging

  # Frontend Static Site (Note: This would be deployed separately on Netlify)
  # Keeping this for reference/alternative deployment option
  - type: static
    name: papzincrew-frontend
    rootDir: frontend/project
    plan: free
    buildCommand: npm ci && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        value: "https://papzincrew-backend.onrender.com"
