[build]
  command = "npm ci && npm run build"
  publish = "dist"

# Proxy API requests to Render backend
[[redirects]]
  from = "/api/*"
  to = "https://papzincrew-backend.onrender.com/:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
