[build]
  command = "npm ci && npm run build"
  publish = "dist"

# Proxy API requests to ngrok backend
[[redirects]]
  from = "/api/*"
  to = "https://REPLACE_WITH_NGROK_URL.ngrok-free.app/:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
